-- PostgreSQL / Supabase. Não execute os arquivos MySQL de database/ neste banco.
-- A tabela agrupa os campos abaixo; a chave primária identifica cada registro.
CREATE TABLE public.sensores (
    -- Identificador PostgreSQL automático; BY DEFAULT também permite IDs explícitos em testes.
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Nome legível do sensor conceitual.
    nome varchar(100) NOT NULL,
    -- Categoria da medição; deve ser única entre os sensores.
    tipo varchar(50) NOT NULL UNIQUE,
    -- Símbolo usado para expressar a medição, como %, °C, m³/s ou MW.
    unidade varchar(20) NOT NULL
);

-- A tabela agrupa os campos abaixo; a chave primária identifica cada registro.
CREATE TABLE public.leituras (
    -- Identificador PostgreSQL automático; BY DEFAULT também permite IDs explícitos em testes.
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Percentual de preenchimento, com duas casas decimais.
    nivel_reservatorio numeric(5,2) NOT NULL CHECK (nivel_reservatorio BETWEEN 0 AND 100),
    -- Temperatura da turbina, com até três algarismos inteiros e duas casas decimais.
    temperatura numeric(5,2) NOT NULL,
    -- Vazão informada em m³/s, com até oito algarismos inteiros e duas casas decimais.
    vazao numeric(10,2) NOT NULL CHECK (vazao >= 0),
    -- Potência gerada em MW, com a mesma precisão da vazão.
    potencia numeric(10,2) NOT NULL CHECK (potencia >= 0),
    -- Estado operacional: verdadeiro/1 para ligada e falso/0 para desligada.
    turbina_ligada boolean NOT NULL,
    -- Classificação calculada pelo PHP: Normal, Atenção ou Crítico.
    status_geral varchar(20) NOT NULL CHECK (status_geral IN ('Normal', 'Atenção', 'Crítico')),
    -- Instante com fuso; o PHP converte para Brasília ao exibir e filtrar.
    data_registro timestamptz NOT NULL DEFAULT now()
);
-- Índice para buscar primeiro as leituras mais recentes e filtrar intervalos de data.
CREATE INDEX leituras_data ON public.leituras (data_registro DESC, id DESC);
-- Índice composto para filtros de situação com data e ordenação estável.
CREATE INDEX leituras_status_data ON public.leituras (status_geral, data_registro DESC, id DESC);

-- A tabela agrupa os campos abaixo; a chave primária identifica cada registro.
CREATE TABLE public.sessoes (
    -- ID de sessão criado pelo PHP e usado para bloquear requisições concorrentes.
    id varchar(128) PRIMARY KEY,
    -- Conteúdo serializado em base64, compatível com a coluna textual do PostgreSQL.
    dados text NOT NULL,
    -- Prazo da sessão em segundos desde a época Unix; a aplicação renova por duas horas.
    expira_em bigint NOT NULL CHECK (expira_em >= 0)
);
-- Índice usado na limpeza periódica de sessões expiradas.
CREATE INDEX sessoes_expiracao ON public.sessoes (expira_em);

-- Cadastra apenas os quatro sensores conceituais; não insere leituras de exemplo.
INSERT INTO public.sensores (nome, tipo, unidade) VALUES
    ('Nível do reservatório', 'nivel', '%'),
    ('Temperatura da turbina', 'temperatura', '°C'),
    ('Vazão de água', 'vazao', 'm³/s'),
    ('Potência gerada', 'potencia', 'MW');

-- O PHP acessa por conexão PostgreSQL no servidor. A API pública do Supabase
-- não deve permitir leitura de sessões nem acesso anônimo às tabelas.
ALTER TABLE public.sensores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leituras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessoes ENABLE ROW LEVEL SECURITY;
-- Remove permissões dos papéis da API; a conexão do servidor mantém seu acesso próprio.
REVOKE ALL ON TABLE public.sensores, public.leituras, public.sessoes FROM anon, authenticated;
-- Impede que os papéis públicos da API obtenham IDs pelas sequências destas tabelas.
REVOKE ALL ON SEQUENCE public.sensores_id_seq, public.leituras_id_seq FROM anon, authenticated;
