-- PostgreSQL / Supabase. Não execute os arquivos MySQL de database/ neste banco.
CREATE TABLE public.sensores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(100) NOT NULL,
    tipo varchar(50) NOT NULL UNIQUE,
    unidade varchar(20) NOT NULL
);

CREATE TABLE public.leituras (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nivel_reservatorio numeric(5,2) NOT NULL CHECK (nivel_reservatorio BETWEEN 0 AND 100),
    temperatura numeric(5,2) NOT NULL,
    vazao numeric(10,2) NOT NULL CHECK (vazao >= 0),
    potencia numeric(10,2) NOT NULL CHECK (potencia >= 0),
    turbina_ligada boolean NOT NULL,
    status_geral varchar(20) NOT NULL CHECK (status_geral IN ('Normal', 'Atenção', 'Crítico')),
    data_registro timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX leituras_data ON public.leituras (data_registro DESC, id DESC);
CREATE INDEX leituras_status_data ON public.leituras (status_geral, data_registro DESC, id DESC);

CREATE TABLE public.sessoes (
    id varchar(128) PRIMARY KEY,
    dados text NOT NULL,
    expira_em bigint NOT NULL CHECK (expira_em >= 0)
);
CREATE INDEX sessoes_expiracao ON public.sessoes (expira_em);

INSERT INTO public.sensores (nome, tipo, unidade) VALUES
    ('Nível do reservatório', 'nivel', '%'),
    ('Temperatura da turbina', 'temperatura', '°C'),
    ('Vazão de água', 'vazao', 'm³/s'),
    ('Potência gerada', 'potencia', 'MW');

-- O PHP acessa por conexão PostgreSQL no servidor. A API pública do Supabase
-- não deve permitir leitura de sessões nem acesso anônimo às tabelas.
ALTER TABLE public.sensores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leituras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessoes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.sensores, public.leituras, public.sessoes FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.sensores_id_seq, public.leituras_id_seq FROM anon, authenticated;
